services:
  overpass:
    image: wiktorn/overpass-api
    container_name: overpass
    ports:
      - "12345:80"
    environment:
      - OVERPASS_META=yes
      - OVERPASS_MODE=init
      - OVERPASS_PLANET_URL=https://download.geofabrik.de/europe/germany/niedersachsen-latest.osm.bz2
    volumes:
      - overpass-db:/db
      - overpass-data:/data
    restart: unless-stopped

volumes:
  overpass-db:
  overpass-data: